name: h2o-lut
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - scipy>=1.12
  - xarray>=2024.1
  - netcdf4
  - h5py
  - pytables
  - pyyaml
  - pandas
  - dask
  - distributed
  - tqdm
  - pip
  - pip:
      - radis>=0.17,<0.18
